#!/usr/bin/env python
from datetime import datetime
import string
import  tkinter as tk
from tkinter import *
from tkinter.filedialog import askdirectory
from include import applib
from include import collection
#initializes the window
app = tk.Tk()
app.title("NSF Soft Sensor Data Collection")
#app.iconphoto()
app.geometry("1200x1000")

#Initialize all existing variables
tk_filename = tk.StringVar()
tk_filename.set("arduino_")

date = datetime.now()
filename_entry = Entry(app, width = 80)


#Create the text at the top and put in to the left
header_label = Label(app, text="To Begin Collecting Data, Please enter the following information", font=("Arial 18 bold"))
header_label.place(relx=0.0, rely=0.001, anchor='nw')
#header_label.pack()

#Create the checkbox
mocap_box = Checkbutton(app, text="Are you Syncing with MOCAP?", variable=tk_filename, onvalue="arduino_mocap_", offvalue="arduino_")
#automatically create the filename for if the use would like to keep it as is
filename = tk_filename.get() + date.strftime("%m_%d_%Y-%H_%M")
mocap_box.place(relx=0.0, rely=0.05, anchor='nw')
#create entry for filename
filename_entry.insert(0, filename)
filename_entry.pack(pady=20)
filename_entry.place(relx=0.001, rely=0.1, anchor='nw')
#filename_entry.bind("<FocusIn>", applib.erase_text(filename_entry))
app.mainloop()